### ISSUE TITLE
Variable engaged settings based on location mode or occupancy status?

### ISSUE THREAD

**Issue by andyhawks** [adey/bangali#15]
I'd love the ability to configure different engaged settings for different modes and possibly current occupancy status. As an example, at Night my timeouts might be shorter and traffic setting lighter than during a Day mode or Entertaining mode.

**Comment by adey** [comment]
interesting idea ... i have considered letting the rules set some key settings. if i did that i think that would address this feature.

**Comment by adey** [comment]
added support for timers to be updated based on last rule executed.
