### ISSUE TITLE
Asleep state

### ISSUE THREAD

**Issue by Johnwillliam** [adey/bangali#33]
Hey mate,

I've a few problems with the asleep state.

1. When switching my asleep sensor to asleep the rooms changes to asleep but all lights turn off and then on again. They should all turn off. Also tried a light rule to do this but it doesn't work.
2. Using a the night button doesnt switch off the lights. 
3. When switching from asleep to awake, some rooms change to occupied (even if there is no motion), some go to checking (which is correct) and some go to engaged. 

I tried to look in your code but it's been to long and you've changed alot haha

**Comment by TonyFleisher** [comment]
I am also noticing that sleep switches don't go off after the noMotionAsleep timer. 
Investigating this today, It looks like a bug was introduced in last version: nightSwitchesOff() in rooms-child-app.groovy was changed to turn switches on instead of turn them off.

**Comment by TonyFleisher** [comment]
I think these issues are all resolved with recent sleep fixes and enhancements
