### ISSUE TITLE
Number format exception when saving room with vents

### ISSUE THREAD

**Issue by kmickeletto** [adey/bangali#40]
Hi,  attempting to set this up and I am getting the following errors when choosing my vents.
> 2825231d-91d1-46f7-b8a9-ca431cca1e8e  9:44:18 PM: error java.lang.NumberFormatException @line 4563 (updateVentIndP)
2825231d-91d1-46f7-b8a9-ca431cca1e8e  9:44:16 PM: error java.lang.NumberFormatException @line 4563 (updateVentIndP)
2825231d-91d1-46f7-b8a9-ca431cca1e8e  9:44:14 PM: error java.lang.NumberFormatException @line 4563 (updateVentIndP)

The vents device handler I am using support these commands.  There are others, but these are the ones I figured you would need to be able to utilize.

> 		
		command "getVentInfo"
		command "getVentStates"
		command "getVentSensorReadings"
		command "getLevel"
		command "getOnOff"
		command "getPressure"
		command "getBattery"
		command "getTemperature"
		command "clearObstruction"
		command "ventFifty"
		command "ventHundred"
		command "ventLevelUp"
		command "ventLevelDown"
		command "setVent"

These are Flair vents.  I can provide additional information or logs if needed.

Project seems really cool, excited to see what it can do for my house!
Thanks!
Ken

**Comment by adey** [comment]
could you please share the capabilities section? looking to check. if it support switch and level.

thank you.

**Comment by kmickeletto** [comment]
Here you are.  I was able to create a temporary workaround by creating virtual switches and linking the state of the virtual switch to the physical vent switch, but this is obviously not ideal.

	definition(name: "My Flair Vent", namespace: "yracine", author: "Yves Racine") {
		capability "Switch Level"
		capability "Switch"
		capability "Refresh"
		capability "Sensor"
		capability "Temperature Measurement"
		capability "Actuator"
		capability "Health Check"

**Comment by adey** [comment]
thats strange it has switch and level. please insert the new ifDebug line in the function updateVentP(...) as shown below and share the output from it.

```
def updateVentIndP(evt)   {
//    ifDebug("updateVentIndP", 'info')
    def child = getChildDevice(getRoom())
    ifDebug(roomVents ? "roomVents.currentSwitch: $roomVents.currentSwitch | roomVents.currentLevel: $roomVents.currentLevel" : "no vents")
    if (child)      child.updateVentIndC((!roomVents ? -1 : (roomVents.currentSwitch == 'off' ? 0 : roomVents.currentLevel)));
}

```

**Comment by kmickeletto** [comment]
Hi adey, I updated to the latest code and it is working.  Sorry for the delay here.

I am assuming you integrated this into the update?

**Comment by adey** [comment]
cool. no worries.

yeah i add checking for switch level additional to level.
