### ISSUE TITLE
Asleep time trigger not activating

### ISSUE THREAD

**Issue by kmickeletto** [adey/bangali#42]
Creating a temperature rule for a room and specifying a time trigger for asleep does not ever trigger.

Mode was is night mode which was specified in rule.

Currently I'm manually engaging sleep mode for rooms each night, which does work as expected.

**Comment by adey** [comment]
can you please share the view all settings? i am not exactly sure what you may be trying here, but the state values are used to verify the condition match for the rule. the rules themselves will never trigger a state change.

**Comment by kmickeletto** [comment]
Ahh, gotcha.  When I read the description that stated "trigger time", I figured that meant it would trigger.  Since it is only a time match, that makes sense.

Thanks,
Ken

**Comment by adey** [comment]
its actually a trigger. :-)

but the trigger only checks the specified conditions at that time … it does not set the state itself. see asleep settings for things that set it asleep state.
